// Generated by Tsuchinoko - Python to Rust Transpiler
// Author: Tane Channel Technology

fn sum_all(values: &[i64]) -> i64 {
    let mut total: i64 = 0i64;
    for v in values.iter().cloned() {
        total += v;
    }
    return total;
}
fn head_and_tail(values: &[i64]) -> (i64, Vec<i64>) {
    if values.len() as i64 == 0i64 {
        return (0i64, vec![]);
    }
    let head: i64 = values[(0i64 as usize)];
    let tail: Vec<i64> = (values[(1i64 as usize).min(values.len())..].to_vec()).to_vec();
    return (head, tail);
}
fn apply_sum(nums: &[i64]) -> i64 {
    return sum_all(nums);
}
fn main() {
    println!("{}", "=== V1.2.0 Working Test ===");

    let result1: i64 = sum_all(&vec![1i64, 2i64, 3i64, 4i64, 5i64]);
    println!("{:?}", &format!("sum_all(1,2,3,4,5) = {:?}", result1));

    let (h, t) : (i64, Vec<i64>) = head_and_tail(&vec![10i64, 20i64, 30i64, 40i64]);
    println!("{:?}", &format!("head={:?}", h));

    let result3: i64 = apply_sum(&vec![10i64, 20i64, 30i64]);
    println!("{:?}", &format!("apply_sum([10,20,30]) = {:?}", result3));

    println!("{}", "=== All tests passed! ===");

}
