// Generated by Tsuchinoko - Python to Rust Transpiler
// Author: Tane Channel Technology

mod bridge;
use bridge::PythonBridge;

fn main() {
    let mut py_bridge = bridge::PythonBridge::new()
        .expect("Failed to start Python worker");
    
        let data = serde_json::json!({ "name": vec!["Alice", "Bob", "Charlie"], "age": vec![25i64, 30i64, 35i64] });
        let df: serde_json::Value = {
    let _arg_0 = data;
        py_bridge.call_json::<serde_json::Value>("pandas.DataFrame", &[serde_json::json!(_arg_0)]).unwrap()
    };
        let arr = {

        py_bridge.call_json_method::<serde_json::Value>(df.clone(), "to_numpy", &[]).unwrap()
    };
        let mean_age: serde_json::Value = {
    let _arg_0 = {
    let _arg_0 = "age";
        py_bridge.call_json_method::<serde_json::Value>(df.clone(), "__getitem__", &[serde_json::json!(_arg_0)]).unwrap()
    };
        py_bridge.call_json::<serde_json::Value>("numpy.mean", &[serde_json::json!(_arg_0)]).unwrap()
    };
        println!("{:?}", "DataFrame:");

        println!("{:?}", &df);

        println!("{:?}", "\nNumpy Array (from to_numpy):");

        println!("{:?}", &arr);

        println!("{:?} {:?}", "\nMean Age:", &mean_age);
}

// Note: This code uses the PythonBridge for calling Python libraries.
// Make sure Python is installed and the required libraries are available.
// The Python worker process will be started automatically.

