// Generated by Tsuchinoko - Python to Rust Transpiler
// Author: Tane Channel Technology

mod bridge;
use bridge::PythonBridge;

fn process_data(py_bridge: &mut bridge::PythonBridge, data: serde_json::Value) -> serde_json::Value {
    let df: serde_json::Value = py_bridge.call_json("pandas.DataFrame", &[serde_json::json!(data)]).unwrap();
    println!("{:?}", &df);

    return df;
}
fn main() {
    let mut py_bridge = bridge::PythonBridge::new()
        .expect("Failed to start Python worker");
    
        println!("{:?}", "=== Dict Test ===");

        let data: serde_json::Value = serde_json::json!({ "name": vec!["Alice", "Bob"], "score": vec![80i64, 90i64] });
        process_data(&mut py_bridge, data.clone());

        println!("{:?}", "=== Done ===");
}

// Note: This code uses the PythonBridge for calling Python libraries.
// Make sure Python is installed and the required libraries are available.
// The Python worker process will be started automatically.

